name: fastapi-zapatillas
services:
  fastapi-zapatillas:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: fastapi-zapatillas
    restart: always
    ports:
      - "8000:8000"
    depends_on:
      - zapatillas-db

  zapatillas-db:
    image: mysql
    container_name: zapatillas-mysql
    environment:
      MYSQL_ROOT_PASSWORD: pablo1234
      MYSQL_DATABASE: zapatillas-db
      MYSQL_USER: pablo
      MYSQL_PASSWORD: 1234
    ports:
      - "3307:3306"