name: fastapi-mysql

services:   
  db-mysql:  
    image: mysql 
    container_name: db-mysql   
    environment:  
      MYSQL_ROOT_PASSWORD: quevedo
      MYSQL_DATABASE: seriesdb
      MYSQL_USER: quevedo
      MYSQL_PASSWORD: 1234
    ports:  
      - "3307:3306"